# Generated by Django 3.0.7 on 2020-07-19 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=1000)),
                ('originalPrice', models.IntegerField()),
                ('discountPrice', models.IntegerField()),
                ('isNew', models.BooleanField(default=False)),
                ('hasDiscount', models.BooleanField(default=False)),
                ('stars', models.IntegerField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='productImages')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('dateOfOrder', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('statusOfProduct', models.CharField(max_length=100)),
                ('orderedProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('orderedUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
